services:
  postgres:
    image: postgres:16-alpine
    container_name: nest_learn_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: nest-learn
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '123456'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
